/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CoordinatePoint } from './coordinatePoint';

export interface Address { 
    district?: string;
    civicNumber?: string;
    civicNumber2?: string;
    street?: string;
    city?: string;
    county?: string;
    /**
     * Province/State ISO code
     */
    stateCode?: string;
    /**
     * Province/State full name
     */
    state?: string;
    postalCode?: string;
    /**
     * country ISO code
     */
    countryCode?: string;
    /**
     * country name
     */
    country?: string;
    coordinates?: CoordinatePoint;
    fullAddress?: string;
}