/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

/**
 * An alert object
 */
export interface Alert { 
    /**
     * id of the alert
     */
    id?: string;
    type?: Alert.TypeEnum;
    /**
     * image of the property
     */
    image?: string;
    title?: string;
    /**
     * id of the listing
     */
    listingId?: string;
    address?: Address;
    /**
     * Attribute to be used in the message for priceDrop and sold.
     */
    amount?: number;
    currency?: string;
    createdAt?: Date;
    status?: Alert.StatusEnum;
}
export namespace Alert {
    export type TypeEnum = 'priceDrop' | 'sold' | 'message' | 'newListing';
    export const TypeEnum = {
        PriceDrop: 'priceDrop' as TypeEnum,
        Sold: 'sold' as TypeEnum,
        Message: 'message' as TypeEnum,
        NewListing: 'newListing' as TypeEnum
    };
    export type StatusEnum = 'read' | 'unread';
    export const StatusEnum = {
        Read: 'read' as StatusEnum,
        Unread: 'unread' as StatusEnum
    };
}