/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ApartmentSize = 1 | 2 | 3 | 4 | 5 | 6;

export const ApartmentSize = {
    NUMBER_1: 1 as ApartmentSize,
    NUMBER_2: 2 as ApartmentSize,
    NUMBER_3: 3 as ApartmentSize,
    NUMBER_4: 4 as ApartmentSize,
    NUMBER_5: 5 as ApartmentSize,
    NUMBER_6: 6 as ApartmentSize
};