/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArticleListItemThumbnails } from './articleListItemThumbnails';
import { Language } from './language';

/**
 * An article item
 */
export interface ArticleListItem { 
    /**
     * id of the article
     */
    id?: string;
    title?: string;
    summary?: string;
    publishDate?: Date;
    thumbnailUrl?: string;
    thumbnails?: ArticleListItemThumbnails;
    language?: Language;
    author?: string;
    authorImg?: string;
    publicUrl?: string;
    category?: string;
}