/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The value of the property used only by the property tax authority of the county or municipality in order to bill the taxes properly.
 */
export interface Assessment { 
    value?: number;
    type?: Assessment.TypeEnum;
    date?: string;
}
export namespace Assessment {
    export type TypeEnum = 'building' | 'land';
    export const TypeEnum = {
        Building: 'building' as TypeEnum,
        Land: 'land' as TypeEnum
    };
}