/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BondYieldCmb { 
    direction?: BondYieldCmb.DirectionEnum;
    value?: number;
}
export namespace BondYieldCmb {
    export type DirectionEnum = 'up' | 'down' | 'noChange';
    export const DirectionEnum = {
        Up: 'up' as DirectionEnum,
        Down: 'down' as DirectionEnum,
        NoChange: 'noChange' as DirectionEnum
    };
}