/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ChartIdentifiers = 'medianPrice' | 'daysOnMarket' | 'totalSold' | 'newListings' | 'activeListings' | 'soldPriceDistribution';

export const ChartIdentifiers = {
    MedianPrice: 'medianPrice' as ChartIdentifiers,
    DaysOnMarket: 'daysOnMarket' as ChartIdentifiers,
    TotalSold: 'totalSold' as ChartIdentifiers,
    NewListings: 'newListings' as ChartIdentifiers,
    ActiveListings: 'activeListings' as ChartIdentifiers,
    SoldPriceDistribution: 'soldPriceDistribution' as ChartIdentifiers
};