/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

/**
 * A commercial space
 */
export interface CommercialSpace { 
    /**
     * area in m2
     */
    area?: number;
    /**
     * monthly rent
     */
    rent?: number;
    address?: Address;
    /**
     * Door suite
     */
    suite?: string;
    /**
     * name of the business
     */
    name?: string;
    /**
     * Main business activity
     */
    activity?: string;
}