/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Comparable KPI
 */
export interface CompsKPI { 
    label?: CompsKPI.LabelEnum;
    value?: number;
}
export namespace CompsKPI {
    export type LabelEnum = 'caprate' | 'pricePerDoor' | 'avgRent';
    export const LabelEnum = {
        Caprate: 'caprate' as LabelEnum,
        PricePerDoor: 'pricePerDoor' as LabelEnum,
        AvgRent: 'avgRent' as LabelEnum
    };
}