/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CompsKPI } from './compsKPI';
import { EventType } from './eventType';

export interface Comparable { 
    id?: string;
    price?: number;
    address?: Address;
    kpis?: Array<CompsKPI>;
    eventType?: EventType;
    eventDate?: string;
    imageUrl?: string;
    isChecked?: boolean;
}