/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

/**
 * A contact
 */
export interface Contact { 
    firstName?: string;
    lastName?: string;
    name?: string;
    organisation?: string;
    mobilePhoneNumber?: string;
    residentialPhoneNumber?: string;
    workPhoneNumber?: string;
    workExtension?: string;
    email?: string;
    website?: string;
    address?: Address;
    /**
     * Website or listing URL
     */
    url?: string;
}