/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';

/**
 * A list of expenses for a given year
 */
export interface Expenses { 
    currency?: Currency;
    /**
     * Year of the expense statement
     */
    year?: number;
    municipalTax?: number;
    schoolTax?: number;
    /**
     * Total amount for municipal and school taxes
     */
    totalTaxes?: number;
    insurance?: number;
    electricity?: number;
    /**
     * naturalGas
     */
    oil?: number;
    /**
     * landscaping
     */
    landscaping?: number;
    /**
     * snow removal
     */
    snowRemoval?: number;
    /**
     * publicity
     */
    publicity?: number;
    /**
     * appliances rental
     */
    appliancesRental?: number;
    /**
     * water tank rental
     */
    waterTankRental?: number;
    /**
     * elevators maintenance
     */
    elevators?: number;
    /**
     * accounting
     */
    accounting?: number;
    /**
     * lawyer and legal fees
     */
    legal?: number;
    /**
     * telecom
     */
    telecom?: number;
    /**
     * maintenance
     */
    maintenance?: number;
    /**
     * Total amount paid for utilities (energy, water, etc.)
     */
    totalUtilities?: number;
    /**
     * Total amount for energy expenses
     */
    energy?: number;
    naturalGas?: number;
    other?: number;
    /**
     * other expenses
     */
    others?: Array<any>;
    /**
     * Total other expenses
     */
    totalOthers?: number;
}