/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ExpensesSummary { 
    /**
     * municipal taxes
     */
    municipalTaxes?: number;
    /**
     * school tax
     */
    schoolTaxes?: number;
    /**
     * insurance
     */
    insurance?: number;
    /**
     * electricity
     */
    electricity?: number;
    /**
     * naturalGas
     */
    naturalGas?: number;
    /**
     * maintenance costs
     */
    maintenanceFees?: number;
    otherExpenses?: number;
    salaries?: number;
    managementFees?: number;
    landscaping?: number;
    additionalManagementCosts?: number;
    totalExpenses?: number;
    CAPEX?: number;
    sum?: number;
}