/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of material used for exterior coating
 */
export interface ExteriorCoating { 
    material?: ExteriorCoating.MaterialEnum;
}
export namespace ExteriorCoating {
    export type MaterialEnum = 'agregate' | 'aluminium' | 'fiber cement' | 'brick' | 'concrete' | 'other' | 'stone' | 'stone and concrete' | 'stucco' | 'vinyl' | 'wood' | 'wood fibers';
    export const MaterialEnum = {
        Agregate: 'agregate' as MaterialEnum,
        Aluminium: 'aluminium' as MaterialEnum,
        FiberCement: 'fiber cement' as MaterialEnum,
        Brick: 'brick' as MaterialEnum,
        Concrete: 'concrete' as MaterialEnum,
        Other: 'other' as MaterialEnum,
        Stone: 'stone' as MaterialEnum,
        StoneAndConcrete: 'stone and concrete' as MaterialEnum,
        Stucco: 'stucco' as MaterialEnum,
        Vinyl: 'vinyl' as MaterialEnum,
        Wood: 'wood' as MaterialEnum,
        WoodFibers: 'wood fibers' as MaterialEnum
    };
}