/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of material used for the foundations
 */
export interface FoundationMaterial { 
    material?: FoundationMaterial.MaterialEnum;
}
export namespace FoundationMaterial {
    export type MaterialEnum = 'poured concrete' | 'stones' | 'concrete blocks' | 'concrete slab' | 'other';
    export const MaterialEnum = {
        PouredConcrete: 'poured concrete' as MaterialEnum,
        Stones: 'stones' as MaterialEnum,
        ConcreteBlocks: 'concrete blocks' as MaterialEnum,
        ConcreteSlab: 'concrete slab' as MaterialEnum,
        Other: 'other' as MaterialEnum
    };
}