/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { Lease } from './lease';

/**
 * An income for a given year
 */
export interface GrossIncome { 
    totalIncome?: number;
    residentialIncome?: number;
    commercialIncome?: number;
    incomeBreakdown?: Array<Lease>;
    otherIncome?: { [key: string]: any; };
    currency?: Currency;
    /**
     * Year of the income
     */
    year?: number;
}