/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';

export interface HomeNews { 
    /**
     * id of the listing
     */
    id?: string;
    /**
     * Type of event
     */
    type?: HomeNews.TypeEnum;
    amount?: number;
    currency?: Currency;
}
export namespace HomeNews {
    export type TypeEnum = 'priceDrop' | 'sold' | 'message' | 'newListing';
    export const TypeEnum = {
        PriceDrop: 'priceDrop' as TypeEnum,
        Sold: 'sold' as TypeEnum,
        Message: 'message' as TypeEnum,
        NewListing: 'newListing' as TypeEnum
    };
}