/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HypothesisOutputSummaryOverviewFinancingDetails } from './hypothesisOutputSummaryOverviewFinancingDetails';

export interface HypothesisOutputSummaryOverview { 
    potentialNOI?: number;
    projectedFutureSaleValue?: number;
    dispositionFee?: number;
    preTaxCashFlowSum?: number;
    /**
     * cash on cash percentage
     */
    cashOnCashRate?: number;
    averagePretaxCashFlow?: number;
    principal?: number;
    principalOnCash?: number;
    annualPropertyAppreciation?: number;
    endBalancedPeriod?: number;
    exploitableLeverage?: number;
    equityMultiple?: number;
    /**
     * Net Revenue Management
     */
    nrm?: number;
    /**
     * Gross Rent Multiplier
     */
    grm?: number;
    pricePerUnit?: number;
    normalizedExpenses?: number;
    profitFromSale?: number;
    financingDetails?: Array<HypothesisOutputSummaryOverviewFinancingDetails>;
}