/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HypothesisInput } from './hypothesisInput';
import { HypothesisOutput } from './hypothesisOutput';

export interface Hypothesis { 
    id?: string;
    input?: HypothesisInput;
    output?: HypothesisOutput;
    /**
     * Timestamp at which the hypothesis was created
     */
    createdAt?: Date;
    /**
     * Timestamp at which the hypothesis was last updated
     */
    updatedAt?: Date;
}