/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FinancingCompany } from './financingCompany';

export interface HypothesisOutputRefinanceParameters { 
    interestRate?: number;
    paymentsPerYear?: number;
    iOfnOvern?: number;
    iOvern?: number;
    loanPeriod?: number;
    maximumLoanDollars?: number;
    firstLoanRemainedBalance?: number;
    annuityFactorType3?: number;
    annuityFactorType4?: number;
    refinancingType?: FinancingCompany;
    availableEquity?: number;
}