/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HypothesisOutputEvProjectionValues { 
    LTV?: number;
    DCR?: number;
    amortization?: number;
    qualificationRate?: number;
    yearlyMaintenancePerUnit?: number;
    yearlySalariesPerUnit?: number;
    vacancyRate?: number;
    managementRate?: number;
    effectiveGrossIncome?: number;
    normalizedExpenses?: number;
    normalizedNetIncome?: number;
    mortageDebtCoverageRatio?: number;
    economicValue?: number;
    /**
     * leverage Net Revenue Management
     */
    leverageNRM?: number;
    leverageCapRate?: number;
}