/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HypothesisOutputSecondaryFinancingParameters { 
    ID?: number;
    loanAmount?: number;
    interestRate?: number;
    paymentsPerYear?: number;
    term?: number;
    loanType?: HypothesisOutputSecondaryFinancingParameters.LoanTypeEnum;
    amortization?: number;
    iOfnOvern?: number;
    iOvern?: number;
    loanPeriod?: number;
    annuityFactortype3?: number;
    annuityFactortype4?: number;
}
export namespace HypothesisOutputSecondaryFinancingParameters {
    export type LoanTypeEnum = 1 | 2 | 3 | 4;
    export const LoanTypeEnum = {
        NUMBER_1: 1 as LoanTypeEnum,
        NUMBER_2: 2 as LoanTypeEnum,
        NUMBER_3: 3 as LoanTypeEnum,
        NUMBER_4: 4 as LoanTypeEnum
    };
}