/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Inclusion = 'water' | 'furnished' | 'hotWater' | 'heating' | 'electricity' | 'internet' | 'parking' | 'snowRemoval' | 'petAllowed' | 'fridge' | 'oven' | 'other' | 'washer' | 'dryer' | 'firstMonthFree' | 'lighting';

export const Inclusion = {
    Water: 'water' as Inclusion,
    Furnished: 'furnished' as Inclusion,
    HotWater: 'hotWater' as Inclusion,
    Heating: 'heating' as Inclusion,
    Electricity: 'electricity' as Inclusion,
    Internet: 'internet' as Inclusion,
    Parking: 'parking' as Inclusion,
    SnowRemoval: 'snowRemoval' as Inclusion,
    PetAllowed: 'petAllowed' as Inclusion,
    Fridge: 'fridge' as Inclusion,
    Oven: 'oven' as Inclusion,
    Other: 'other' as Inclusion,
    Washer: 'washer' as Inclusion,
    Dryer: 'dryer' as Inclusion,
    FirstMonthFree: 'firstMonthFree' as Inclusion,
    Lighting: 'lighting' as Inclusion
};