/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataPoint } from './dataPoint';

export interface IndicatorTrend { 
    value?: number;
    /**
     * data can be shown or not
     */
    showData?: boolean;
    historical?: Array<DataPoint>;
}