/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingRowValue } from './listingRowValue';

/**
 * details of expenses
 */
export interface ListingExpenses { 
    taxes?: ListingRowValue;
    insurance?: ListingRowValue;
    utilities?: ListingRowValue;
    management?: ListingRowValue;
    maintenance?: ListingRowValue;
    salaries?: ListingRowValue;
    normalizedExpenses?: ListingRowValue;
}