/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A listing offer made by a user to a building owner
 */
export interface ListingOffer { 
    id?: string;
    listingId?: string;
    /**
     * user who created the offer
     */
    userId?: string;
    price?: number;
    /**
     * number of days the offer is valid
     */
    validFor?: number;
    /**
     * How the person wants to be contacted
     */
    contactMeBy?: Array<ListingOffer.ContactMeByEnum>;
    /**
     * condition prior to make the offer effective
     */
    conditions?: Array<ListingOffer.ConditionsEnum>;
    otherConditions?: string;
    createdAt?: Date;
    /**
     * status of the offer
     */
    status?: string;
}
export namespace ListingOffer {
    export type ContactMeByEnum = 'phone' | 'email';
    export const ContactMeByEnum = {
        Phone: 'phone' as ContactMeByEnum,
        Email: 'email' as ContactMeByEnum
    };
    export type ConditionsEnum = 'preInspection' | 'visit';
    export const ConditionsEnum = {
        PreInspection: 'preInspection' as ConditionsEnum,
        Visit: 'visit' as ConditionsEnum
    };
}