/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ListingStatuses = 'sold' | 'forSale' | 'destroyed' | 'expired' | 'canceled';

export const ListingStatuses = {
    Sold: 'sold' as ListingStatuses,
    ForSale: 'forSale' as ListingStatuses,
    Destroyed: 'destroyed' as ListingStatuses,
    Expired: 'expired' as ListingStatuses,
    Canceled: 'canceled' as ListingStatuses
};