/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * type of listing (public, pocket, offmarket)
 */
export type ListingType = 'pocket' | 'public' | 'offMarket';

export const ListingType = {
    Pocket: 'pocket' as ListingType,
    Public: 'public' as ListingType,
    OffMarket: 'offMarket' as ListingType
};