/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeSeriesChartItem } from './timeSeriesChartItem';

export interface MacroDataHistorical { 
    bondMarketable13y?: TimeSeriesChartItem;
    bondMarketable35y?: TimeSeriesChartItem;
    bondMarketable510y?: TimeSeriesChartItem;
    bondMarketable10y?: TimeSeriesChartItem;
    bondGoc2y?: TimeSeriesChartItem;
    bondGoc3y?: TimeSeriesChartItem;
    bondGoc5y?: TimeSeriesChartItem;
    bondGoc7y?: TimeSeriesChartItem;
    bondGoc10y?: TimeSeriesChartItem;
    bondGocLong?: TimeSeriesChartItem;
    interestRateFixed1y?: TimeSeriesChartItem;
    interestRateFixed2y?: TimeSeriesChartItem;
    interestRateFixed3y?: TimeSeriesChartItem;
    interestRateFixed4y?: TimeSeriesChartItem;
    interestRateFixed5y?: TimeSeriesChartItem;
    interestRateFixed6y?: TimeSeriesChartItem;
    interestRateFixed7y?: TimeSeriesChartItem;
    interestRateFixed8y?: TimeSeriesChartItem;
    interestRateFixed9y?: TimeSeriesChartItem;
    interestRateFixed10y?: TimeSeriesChartItem;
    interestRateVariable3y?: TimeSeriesChartItem;
    interestRateVariable5y?: TimeSeriesChartItem;
}