/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';

/**
 * A maintenance action that resulted in an improvement of the building features
 */
export interface Maintenance { 
    /**
     * Amount paid
     */
    price?: number;
    currency?: Currency;
    /**
     * The date at which the maintenance activity occured
     */
    date?: string;
    /**
     * The feature improved
     */
    type?: Maintenance.TypeEnum;
    /**
     * Detail about the feature improvement
     */
    description?: string;
    /**
     * percentage of the feature improved
     */
    ratio?: number;
}
export namespace Maintenance {
    export type TypeEnum = 'balconies' | 'basement' | 'bathroom' | 'boiler' | 'exteriorCoating' | 'floors' | 'foundation' | 'heating' | 'insulation' | 'kitchen' | 'other' | 'roof' | 'windows';
    export const TypeEnum = {
        Balconies: 'balconies' as TypeEnum,
        Basement: 'basement' as TypeEnum,
        Bathroom: 'bathroom' as TypeEnum,
        Boiler: 'boiler' as TypeEnum,
        ExteriorCoating: 'exteriorCoating' as TypeEnum,
        Floors: 'floors' as TypeEnum,
        Foundation: 'foundation' as TypeEnum,
        Heating: 'heating' as TypeEnum,
        Insulation: 'insulation' as TypeEnum,
        Kitchen: 'kitchen' as TypeEnum,
        Other: 'other' as TypeEnum,
        Roof: 'roof' as TypeEnum,
        Windows: 'windows' as TypeEnum
    };
}