/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MarketPropertyTrendIdentifiers = 'avgRent' | 'avgRentPercentiles' | 'vacancyRate' | 'vacancyRateMarket' | 'historicalRent' | 'comparison';

export const MarketPropertyTrendIdentifiers = {
    AvgRent: 'avgRent' as MarketPropertyTrendIdentifiers,
    AvgRentPercentiles: 'avgRentPercentiles' as MarketPropertyTrendIdentifiers,
    VacancyRate: 'vacancyRate' as MarketPropertyTrendIdentifiers,
    VacancyRateMarket: 'vacancyRateMarket' as MarketPropertyTrendIdentifiers,
    HistoricalRent: 'historicalRent' as MarketPropertyTrendIdentifiers,
    Comparison: 'comparison' as MarketPropertyTrendIdentifiers
};