/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Comparable } from './comparable';
import { CompsKPI } from './compsKPI';

/**
 * A market property comparables
 */
export interface MarketPropertyComparable { 
    potentialPrice?: number;
    address?: Address;
    kpis?: Array<CompsKPI>;
    comparables?: Array<Comparable>;
}