/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

/**
 * A small object for properties used in search results
 */
export interface ModelPropertyShort { 
    id?: string;
    address?: Address;
    /**
     * Number of residential units (apartments) in the building
     */
    residentialUnits?: number;
    /**
     * Source of the property info
     */
    provider?: ModelPropertyShort.ProviderEnum;
    yearOfConstruction?: number;
    /**
     * image of the property
     */
    image?: string;
}
export namespace ModelPropertyShort {
    export type ProviderEnum = 'gmap' | 'mrex';
    export const ProviderEnum = {
        Gmap: 'gmap' as ProviderEnum,
        Mrex: 'mrex' as ProviderEnum
    };
}