/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A latitude and longitude point coordinate with a radius
 */
export interface Near { 
    type?: Near.TypeEnum;
    coordinates?: Array<number>;
    /**
     * Distance in meters
     */
    maxDistance?: number;
}
export namespace Near {
    export type TypeEnum = 'Point';
    export const TypeEnum = {
        Point: 'Point' as TypeEnum
    };
}