/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * New token POST body
 */
export interface NewTokenBody { 
    /**
     * Provider token
     */
    token?: string;
    provider?: NewTokenBody.ProviderEnum;
    /**
     * provider user identifier
     */
    id?: string;
}
export namespace NewTokenBody {
    export type ProviderEnum = 'facebook' | 'apple' | 'google';
    export const ProviderEnum = {
        Facebook: 'facebook' as ProviderEnum,
        Apple: 'apple' as ProviderEnum,
        Google: 'google' as ProviderEnum
    };
}