/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OperationalCashFlow { 
    income?: number;
    productRefinance?: number;
    operationExpenses?: number;
    paymentMortgage?: number;
    secondaryFinancePayment?: number;
    refinancePayment?: number;
    mangement?: number;
    CAPEX?: number;
    tax?: number;
    operationalFlow?: number;
}