/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OptimisationExpenses { 
    municipalTaxes?: number;
    schoolTaxes?: number;
    insurance?: number;
    electricity?: number;
    naturalGas?: number;
    totalRealExpenses?: number;
    yearlyMaintenancePerUnit?: number;
    yearlySalaryPerUnit?: number;
    outdoorMaintenance?: number;
    managementRate?: number;
    otherExpenses?: number;
    managementFees?: number;
    totalSalaries?: number;
    maintenanceFees?: number;
    totalExpenses?: number;
}