/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { PortfolioFeedItem } from './portfolioFeedItem';
import { PortfolioPropertyShort } from './portfolioPropertyShort';
import { PortfolioSummary } from './portfolioSummary';
import { PortfolioSummaryIndicatorsTrends } from './portfolioSummaryIndicatorsTrends';
import { PortfolioSummaryMetrics } from './portfolioSummaryMetrics';
import { ReceiveOfferStatus } from './receiveOfferStatus';
import { UpcomingRefinance } from './upcomingRefinance';

/**
 * MREX Portfolio of portfolio
 */
export interface PortfolioPropertySummary extends PortfolioSummary { 
    propertyId?: string;
    addressStr?: string;
    address?: Address;
    city?: string;
    listingId?: string;
    status?: ReceiveOfferStatus;
    feed?: Array<PortfolioFeedItem>;
    imageUrl?: string;
    /**
     * Whether or not the portfolio is ready to be shown
     */
    isProcessing?: boolean;
    yearOfConstruction?: number;
}