/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { PortfolioPropertyStatus } from './portfolioPropertyStatus';
import { PropertyType } from './propertyType';
import { ReceiveOfferStatus } from './receiveOfferStatus';

export interface PortfolioPropertyShort { 
    portfolioId?: string;
    propertyId?: string;
    imageUrl?: string;
    price?: number;
    address?: Address;
    receiveOfferStatus?: ReceiveOfferStatus;
    propertyType?: PropertyType;
    modelsCount?: number;
    /**
     * Number of residential units (apartments) in the building
     */
    residentialUnits?: number;
    /**
     * Year of the construction
     */
    yearOfConstruction?: number;
    /**
     * Whether or not the portfolio is ready to be shown
     */
    isProcessing?: boolean;
    portfolioStatus?: PortfolioPropertyStatus;
}