/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A video link
 */
export interface PropertyVideo { 
    type?: PropertyVideo.TypeEnum;
    primary?: boolean;
    label?: string;
    /**
     * alternative text to show in the alt tag
     */
    alt?: string;
    description?: string;
    formats?: any;
}
export namespace PropertyVideo {
    export type TypeEnum = 'mp4';
    export const TypeEnum = {
        Mp4: 'mp4' as TypeEnum
    };
}