/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FinancingCompany } from './financingCompany';

/**
 * details of qualification rates for each bank
 */
export interface QualificationRate { 
    financingCompany?: FinancingCompany;
    amortization?: number;
    /**
     * vacancy rate in %
     */
    vacancyRate?: number;
    /**
     * loan to value in%
     */
    ltv?: number;
    /**
     * deb coverage ratio
     */
    debtCoverageRatio?: number;
    /**
     * interest rate in %
     */
    interestRate?: number;
}