/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ListingType } from './listingType';

export interface RecentlySoldHome { 
    /**
     * id of the listing
     */
    id?: string;
    publishDate?: Date;
    soldDate?: Date;
    soldDays?: number;
    /**
     * image of the property
     */
    image?: string;
    address?: Address;
    residentialUnits?: number;
    yearOfConstruction?: number;
    listingType?: ListingType;
}