/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FinancingCompany } from './financingCompany';

export interface RefinancingInputs { 
    timing?: number;
    loanAmount?: number;
    qualificationRate?: number;
    paymentsPerYear?: number;
    /**
     * Term of the lean
     */
    term?: number;
    /**
     * 4 types of different projections
     */
    loanType?: RefinancingInputs.LoanTypeEnum;
    amortization?: number;
    refinancingType?: FinancingCompany;
    refinancingBank?: FinancingCompany;
}
export namespace RefinancingInputs {
    export type LoanTypeEnum = 1 | 2 | 3 | 4;
    export const LoanTypeEnum = {
        NUMBER_1: 1 as LoanTypeEnum,
        NUMBER_2: 2 as LoanTypeEnum,
        NUMBER_3: 3 as LoanTypeEnum,
        NUMBER_4: 4 as LoanTypeEnum
    };
}