/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Number of apartments and their size
 */
export interface ResidentialDistribution { 
    /**
     * studio
     */
    _1?: number;
    /**
     * 2.5
     */
    _2?: number;
    /**
     * 3.5
     */
    _3?: number;
    /**
     * 4.5
     */
    _4?: number;
    /**
     * 5.5
     */
    _5?: number;
    /**
     * 6.5 and more
     */
    _6?: number;
}