/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of material used for the roof. See \"https://westroofingsystems.com/5-types-of-commercial-roofing/\"\" for more details
 */
export interface RoofMaterial { 
    material?: RoofMaterial.MaterialEnum;
}
export namespace RoofMaterial {
    export type MaterialEnum = 'asphalt shingles' | 'Bitumen and gravel' | 'Clay / Concrete Tiles' | 'Slate' | 'Wood Shingles and Shake' | 'Spray Polyurethane Foam' | 'Single-Ply Membrane' | 'Metal' | 'Built-Up' | 'Elastomeric Membrane';
    export const MaterialEnum = {
        AsphaltShingles: 'asphalt shingles' as MaterialEnum,
        BitumenAndGravel: 'Bitumen and gravel' as MaterialEnum,
        ClayConcreteTiles: 'Clay / Concrete Tiles' as MaterialEnum,
        Slate: 'Slate' as MaterialEnum,
        WoodShinglesAndShake: 'Wood Shingles and Shake' as MaterialEnum,
        SprayPolyurethaneFoam: 'Spray Polyurethane Foam' as MaterialEnum,
        SinglePlyMembrane: 'Single-Ply Membrane' as MaterialEnum,
        Metal: 'Metal' as MaterialEnum,
        BuiltUp: 'Built-Up' as MaterialEnum,
        ElastomericMembrane: 'Elastomeric Membrane' as MaterialEnum
    };
}