/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingType } from './listingType';

export interface SearchCriteriaListing { 
    /**
     * Include listings within distance (km)
     */
    distance?: number;
    /**
     * Price range
     */
    price?: Array<number>;
    /**
     * How many days on market
     */
    publishDays?: Array<number>;
    /**
     * Cash down required range
     */
    cashdown?: Array<number>;
    /**
     * Range for number of units
     */
    residentialUnits?: Array<number>;
    /**
     * Range of year of construction
     */
    yearOfConstruction?: Array<number>;
    listingType?: Array<ListingType>;
    /**
     * Whether or not the owner accepts non-solicited offers
     */
    acceptOffers?: boolean;
    /**
     * Whether or not include listing that the owner doesn't accept unsolicited offers
     */
    notAcceptOffers?: boolean;
}