/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Heating } from './heating';
import { ListingType } from './listingType';
import { PropertyType } from './propertyType';

/**
 * A small object for listings used in search results
 */
export interface SearchResult { 
    id?: string;
    address?: Address;
    /**
     * distance in meter from address provided in the search
     */
    distance?: number;
    propertyType?: PropertyType;
    /**
     * Number of residential units (apartments) in the building
     */
    residentialUnits?: number;
    /**
     * image of the property
     */
    image?: string;
    /**
     * List of images
     */
    images?: Array<string>;
    /**
     * Official Asking price
     */
    askPrice?: number;
    /**
     * Year of the construction
     */
    yearOfConstruction?: number;
    /**
     * Type of heating used and distribution
     */
    heating?: Array<Heating>;
    listingType?: ListingType;
    /**
     * Used for private listingType. Address fields and price are hidden unless the owner agrees to share its data with the investor
     */
    hideFields?: boolean;
    caprate?: number;
    listingId?: string;
    propertyId?: string;
    /**
     * Timestamp at which the listing was created
     */
    createdAt?: Date;
}