/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Contact } from './contact';

/**
 * Contact of the seller (current owner or broker). A property sold by the owner doesn't involve a broker
 */
export interface Seller { 
    type?: Seller.TypeEnum;
    contact?: Contact;
}
export namespace Seller {
    export type TypeEnum = 'seller' | 'broker';
    export const TypeEnum = {
        Seller: 'seller' as TypeEnum,
        Broker: 'broker' as TypeEnum
    };
}