/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';

/**
 * A sell price object that contains the price at a given time
 */
export interface SellPrice { 
    /**
     * Sell price amount
     */
    price?: number;
    currency?: Currency;
    /**
     * The date the sell price was created/updated
     */
    date?: string;
    /**
     * The asking price or sold price
     */
    type?: SellPrice.TypeEnum;
}
export namespace SellPrice {
    export type TypeEnum = 'ask' | 'sold';
    export const TypeEnum = {
        Ask: 'ask' as TypeEnum,
        Sold: 'sold' as TypeEnum
    };
}