/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Language } from './language';

/**
 * Signup object
 */
export interface Signup { 
    firstname?: string;
    lastname?: string;
    age?: number;
    email?: string;
    phoneNumber?: string;
    password?: string;
    verifyCode?: string;
    language?: Language;
}