/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Contact } from './contact';
import { Currency } from './currency';
import { Source } from './source';

/**
 * a property transaction
 */
export interface Transaction { 
    /**
     * Sold price
     */
    price?: number;
    buyer?: Array<Contact>;
    seller?: Array<Contact>;
    broker?: Array<Contact>;
    /**
     * The date the transaction was done
     */
    date?: Date;
    /**
     * Id of the property
     */
    property?: string;
    currency?: Currency;
    /**
     * An array that represent where the data comes from
     */
    source?: Array<Source>;
    /**
     * Version of the algorithm who processed the document
     */
    version?: string;
    /**
     * number of days to sell the property
     */
    saleDelay?: number;
}