/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserCommentType } from './userCommentType';

/**
 * User comment
 */
export interface UserCommentListItem { 
    subject?: string;
    type?: UserCommentType;
    message?: string;
    status?: UserCommentListItem.StatusEnum;
}
export namespace UserCommentListItem {
    export type StatusEnum = 'new' | 'closed' | 'processing';
    export const StatusEnum = {
        New: 'new' as StatusEnum,
        Closed: 'closed' as StatusEnum,
        Processing: 'processing' as StatusEnum
    };
}