/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A user notice of interest
 */
export interface UserNotice { 
    name?: string;
    email?: string;
    phoneNumber?: string;
    message?: string;
    listingId?: string;
    propertyId?: string;
    contactPreference?: Array<UserNotice.ContactPreferenceEnum>;
}
export namespace UserNotice {
    export type ContactPreferenceEnum = 'email' | 'phone';
    export const ContactPreferenceEnum = {
        Email: 'email' as ContactPreferenceEnum,
        Phone: 'phone' as ContactPreferenceEnum
    };
}