/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Coordinate } from './coordinate';
import { DeviceInfo } from './deviceInfo';
import { Language } from './language';
import { UserSubscription } from './userSubscription';

/**
 * User object
 */
export interface User { 
    id?: string;
    firstname?: string;
    lastname?: string;
    name?: string;
    language?: Language;
    email?: string;
    phoneNumber?: string;
    photoUrl?: string;
    newslettersSubscribe?: boolean;
    notificationsSubscribe?: boolean;
    address?: Address;
    favoriteListings?: Array<string>;
    scopes?: Array<string>;
    subscription?: UserSubscription;
    limits?: any;
    roles?: Array<string>;
    /**
     * Data that can be attached to the user
     */
    metadata?: any;
    /**
     * Timestamp at which the hypothesis was last updated
     */
    updatedAt?: Date;
    /**
     * User ratios about his subscriptions
     */
    usage?: any;
    deviceInfo?: DeviceInfo;
    coordinate?: Coordinate;
}