/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A blog video article
 */
export interface VideoBlog { 
    /**
     * id of video
     */
    id?: string;
    title?: string;
    publishDate?: Date;
    videoUrl?: string;
    summary?: string;
    html?: string;
    thumbnailUrl?: string;
    publicUrl?: string;
}