/**
 * MREX property schema
 * This is the MREX schema for a property
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlavoie@mrex.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Heating } from './heating';
import { ListingType } from './listingType';
import { ModelProperty } from './modelProperty';
import { Picture } from './picture';
import { PropertyType } from './propertyType';

/**
 * Watchlist property
 */
export interface WatchlistProperty { 
    id?: string;
    askPrice?: number;
    propertyType?: PropertyType;
    residentialUnits?: number;
    image?: string;
    pictures?: Array<Picture>;
    yearOfConstruction?: number;
    heating?: Array<Heating>;
    address?: Address;
    createdAt?: Date;
    propertyId?: string;
    inheritedFrom?: string;
    listingType?: ListingType;
    models?: Array<ModelProperty>;
    isMREXproperty?: boolean;
}