export const Plans = {
	Basic: [
		{ id: 'watchlist_items', status: true },
		{ id: 'comp_selection', status: true },
		{ id: 'view_every_publically', status: true },
		{ id: 'off_market_listings', status: true },
		{ id: 'add_your_properties', status: true },
		{ id: 'portfolio_monitoring_kpi', status: true },
		{ id: 'consult_pocket_listings', status: false },
		{ id: 'view_statistical_data', status: false },
		{ id: 'sales_comp', status: false },
		{ id: 'see_advanced_portfolio_metrics', status: false },
		{ id: 'receive_alerts_based_equity', status: false },
		{ id: 'choose_direct_sales', status: false },
		{ id: 'create_models_for_crunched', status: false },
		{ id: 'ai_powered_stats', status: false },
		{ id: 'advanced_home_screening', status: false },
	],
	Professional : [
		{ id: 'watchlist_items', status: true },
		{ id: 'comp_selection', status: true },
		{ id: 'view_every_publically', status: true },
		{ id: 'off_market_listings', status: true },
		{ id: 'add_your_properties', status: true },
		{ id: 'portfolio_monitoring_kpi', status: true },
		{ id: 'consult_pocket_listings', status: true },
		{ id: 'view_statistical_data', status: true },
		{ id: 'sales_comp', status: true },
		{ id: 'see_advanced_portfolio_metrics', status: true },
		{ id: 'receive_alerts_based_equity', status: true },
		{ id: 'choose_direct_sales', status: true },
		{ id: 'create_models_for_crunched', status: true },
		{ id: 'ai_powered_stats', status: true },
		{ id: 'advanced_home_screening', status: true },
	],
	Premium: [
		{ id: 'watchlist_items', status: true },
		{ id: 'comp_selection', status: true },
		{ id: 'view_every_publically', status: true },
		{ id: 'off_market_listings', status: true },
		{ id: 'add_your_properties', status: true },
		{ id: 'portfolio_monitoring_kpi', status: true },
		{ id: 'consult_pocket_listings', status: true },
		{ id: 'view_statistical_data', status: true },
		{ id: 'sales_comp', status: true },
		{ id: 'see_advanced_portfolio_metrics', status: true },
		{ id: 'receive_alerts_based_equity', status: true },
		{ id: 'choose_direct_sales', status: true },
		{ id: 'create_models_for_crunched', status: false },
		{ id: 'ai_powered_stats', status: false },
		{ id: 'advanced_home_screening', status: false },
	],
	Verified: [
		{ id: 'watchlist_items', status: true },
		{ id: 'comp_selection', status: true },
		{ id: 'view_every_publically', status: true },
		{ id: 'off_market_listings', status: true },
		{ id: 'add_your_properties', status: true },
		{ id: 'portfolio_monitoring_kpi', status: true },
		{ id: 'consult_pocket_listings', status: true },
		{ id: 'view_statistical_data', status: true },
		{ id: 'sales_comp', status: false },
		{ id: 'see_advanced_portfolio_metrics', status: false },
		{ id: 'receive_alerts_based_equity', status: false },
		{ id: 'choose_direct_sales', status: false },
		{ id: 'create_models_for_crunched', status: false },
		{ id: 'ai_powered_stats', status: false },
		{ id: 'advanced_home_screening', status: false },
	]
};
